- README.md
- rumq-cli/Cargo.toml
- rumq-client/Cargo.toml
- rumq-client/examples/gcloud.rs
- rumq-client/examples/pubsub.rs
- rumq-client/examples/smoke.rs
- rumq-client/src/eventloop.rs
- rumq-client/src/lib.rs
- rumq-client/src/state.rs
- rumq-core/Cargo.toml
* Make connections part of stream
* Remove reconnection options from stream
* Add discord link
> Connection stream

- rumq-client/src/lib.rs
This allows `let req: Request = subscribe(...).into()`.
> Added Into for Request

- rumq-client/Cargo.toml
Required by `tokio::time::throttle`
fixes #38
> Enable "stream" tokio feature

- rumq-broker/Cargo.toml
- rumq-client/Cargo.toml
- rumq-core/Cargo.toml
- rumq-core/src/mqtt4/codec.rs
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
> Bump tokio-util to 0.3 and adjust Encoder use

- rumq-broker/Cargo.toml
- rumq-client/Cargo.toml
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
> Bump tokio-rustls dependency

- rumq-client/src/eventloop.rs
@tekjar First of all, Thank you for your hard work on this repo! :smiley_cat: 
I'm in the process of learning **MQTT**,
and I hope I could meaningfully contribute to this repo soon :smiley: 
This PR contains minor refactorings which won't affect the program logic.
> minor refactorings

- rumq-client/src/eventloop.rs
> Use max_packet_size from options

- mqtt4bytes/Cargo.toml
- mqtt4bytes/src/lib.rs
- mqtt4bytes/src/read.rs
- mqtt4bytes/tests/smoke.rs
- More tests
- Smoke test which simulates data fill randomness of codec
Fixes #69
> More tests

- rumq-client/examples/gcloud.rs
- rumq-client/examples/pubsub.rs
- rumq-client/examples/reconnection.rs
- rumq-client/examples/smoke.rs
- rumq-client/examples/tls.rs
- rumq-client/src/eventloop.rs
> make requests generic instead of boxed

- rumqttlog/src/storage/segment.rs
`rumqttlog` - and by extension its dependents - cannot currently be compiled on and for Windows because `std::os::unix` is used unconditionally in the `segment` module. This change adds a conditionally-compiled inline function that keeps the current code for Unix systems while implementing a slightly different version for Windows.
> Fix compilation on Windows

- rumqttc/src/state.rs
> Handle disconnect requests.

- mqtt4bytes/src/packets/connect.rs
- mqtt4bytes/src/packets/mod.rs
This also adds a constructor, consistent with Publish.
Fixes #122.
> Use Bytes rather than String for LastWill.

- rumqttc/examples/asyncpubsub.rs
- rumqttc/src/client.rs
- rumqttc/src/eventloop.rs
I somehow forgot to fix these in my last pull request.
> Fix warnings.

- mqtt4bytes/Cargo.toml
- mqtt5bytes/Cargo.toml
- rumqttc/Cargo.toml
- rumqttd/Cargo.toml
This may make it easier for people to find these crates.
> Add keywords and categories for crates.io.

- mqtt4bytes/Cargo.toml
- mqtt5bytes/Cargo.toml
- rumqttc/Cargo.toml
- rumqttc/README.md
- rumqttc/examples/syncpubsub.rs
- rumqttc/src/client.rs
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
- rumqttc/src/state.rs
- rumqttd/Cargo.toml
- rumqttlog/Cargo.toml
> Unsubscribe implementation and 0.1

- rumqttc/Cargo.toml
- rumqttc/src/eventloop.rs
- rumqttc/src/framed.rs
- rumqttc/src/lib.rs
- rumqttc/src/state.rs
- rumqttd/src/network.rs
- rumqttlog/src/router/router.rs
- rumqttlog/src/router/slab.rs
- rumqttlog/src/router/watermarks.rs
- rumqttlog/src/storage/index.rs
- rumqttlog/src/volatile/mod.rs
Not all of them, but a decent amount.
> Fix clippy warnings

- rumqttc/README.md
In #163 @tekjar suggested I add this detail to the readme. I reorganised it a bit to make it a bit easier to find (I hope).
> Added note about TLS bare IP address limitation

- mqtt4bytes/Cargo.toml
- rumqttc/Cargo.toml
- rumqttc/examples/asyncpubsub.rs
- rumqttc/src/client.rs
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
- rumqttc/tests/broker.rs
- rumqttc/tests/reliability.rs
- rumqttd/Cargo.toml
- rumqttd/src/consolelink.rs
- rumqttd/src/lib.rs
- rumqttd/src/network.rs
- rumqttd/src/remotelink.rs
- rumqttd/src/replicationlink/link.rs
- rumqttd/src/replicationlink/mod.rs
- rumqttlog/Cargo.toml
> Update tokio to 0.3

- LICENSE
- README.md
> Add LICENSE file with Apache 2.0 text

- benchmarks/Cargo.toml
- benchmarks/mesh.rs
- benchmarks/pahoasync.rs
- benchmarks/routernxn.rs
- benchmarks/rumqttasync.rs
- benchmarks/rumqttasyncqos0.rs
- mqtt4bytes/Cargo.toml
- mqtt5bytes/Cargo.toml
- mqtt5bytes/examples/pubsub.rs
- mqtt5bytes/src/packets/mod.rs
- mqtt5bytes/src/packets/subscribe.rs
- rumqttc/Cargo.toml
- rumqttc/README.md
- rumqttc/src/eventloop.rs
- rumqttd/Cargo.toml
- rumqttlog/Cargo.toml
- rumqttlog/src/router/router.rs
- rumqttlog/tests/mesh.rs
The `packet_id_collisions_are_detected_and_flow_control_is_applied` test is failing, but it was failing already before. All other tests pass.
This fixes #217.
> Upgrade to Tokio 1.0

- rumqttd/Cargo.toml
- rumqttd/examples/async_broker.rs
- rumqttd/examples/broker.rs
- rumqttd/src/async_locallink.rs
- rumqttd/src/lib.rs
- rumqttd/src/locallink.rs
> Async link try 3 (now with tokio 1.0)

- rumqttd/examples/async_broker.rs
- rumqttd/src/async_locallink.rs
- rumqttd/src/consolelink.rs
- rumqttd/src/lib.rs
Added a teeny tiny bit of documentation re the deadlock as well
> Reenable async_locallink with async consolelink

- mqttbytes/Cargo.toml
- rumqttd/Cargo.toml
- rumqttlog/Cargo.toml
- rumqttmesh/Cargo.toml
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
> Add repository links to Cargo.toml

- mqttbytes/src/v4/connect.rs
- mqttbytes/src/v5/connect.rs
Align with the `protocol` field of v4 connect.
> Set protocol field of v5 connect packet to pub

- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
Adds support for unix domain sockets.  Resolves #307.
> Add unix domain socket support

- rumqttc/Cargo.toml
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
Without this feature it works only on unix platforms
Related to #306
> Add unix feature

- mqttbytes/src/v4/connect.rs
- mqttbytes/src/v5/connect.rs
- rumqttc/src/lib.rs
> Use separate type bounds for arguments

- mqttbytes/src/v4/pubcomp.rs
- mqttbytes/src/v4/pubrec.rs
- mqttbytes/src/v4/pubrel.rs
- mqttbytes/src/v5/pubcomp.rs
- mqttbytes/src/v5/pubrec.rs
- mqttbytes/src/v5/pubrel.rs
> Fix documentation for PUB* packets

- .github/workflows/features.yml
this should prevent mistakes
windows fails should be fixed by #317.
Its not clear to my why macOS fails.
See running example: https://github.com/EdJoPaTo/rumqtt/actions/workflows/features.yml
> Improve CI testing

- rumqttd/src/state.rs
> return all QoS0 packets from pending

- .github/workflows/release.yml
**Objectives**
- Automate releasing rumqttc and rumqttd to crates.io
> Write a GitHub Action to automate releasing to crates.io

- .github/workflows/features.yml
- rumqttc/examples/async_manual_acks.rs
- rumqttc/examples/websocket.rs
- rumqttc/src/mqttbytes/mod.rs
- rumqttc/tests/reliability.rs
- rumqttd/Cargo.toml
- rumqttd/src/lib.rs
- rumqttd/src/main.rs
- rumqttd/src/mqttbytes/mod.rs
Changes to solve issues with CI observed on Windows and Mac OS.
> Fix CI for rumqtt Mac and Windows

- rumqttc/src/state.rs
> rumqttc: convert all direct index access to `get_mut`

- rumqttc/src/client.rs
- rumqttc/src/mqttbytes/mod.rs
- rumqttc/src/mqttbytes/v4/subscribe.rs
- rumqttc/src/state.rs
- rumqttc/src/v5/client/asyncclient.rs
- rumqttc/src/v5/client/mod.rs
- rumqttc/src/v5/client/syncclient.rs
- rumqttc/src/v5/packet/mod.rs
- rumqttc/src/v5/packet/subscribe.rs
Return Error in case of empty filter list
> Handle subscription with empty filter

- rumqttc/src/state.rs
> Fix missing self.inflight += 1

- rumqttc/src/v5/client/asyncclient.rs
> feat: add subscribe/unsubscribe properties

- rumqttc/Cargo.toml
- rumqttd/Cargo.toml
> fix(dependency): Revert back tokio version to `1`

- rumqttc/src/v5/packet/connack.rs
- rumqttc/src/v5/packet/connect.rs
- rumqttc/src/v5/packet/disconnect.rs
- rumqttc/src/v5/packet/puback.rs
- rumqttc/src/v5/packet/pubcomp.rs
- rumqttc/src/v5/packet/publish.rs
- rumqttc/src/v5/packet/pubrec.rs
- rumqttc/src/v5/packet/pubrel.rs
- rumqttc/src/v5/packet/suback.rs
- rumqttc/src/v5/packet/subscribe.rs
- rumqttc/src/v5/packet/unsuback.rs
- rumqttc/src/v5/packet/unsubscribe.rs
ref: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Properties
> fix(serialization): Serialize no properties as 0x0 byte

- rumqttc/README.md
> Correct statement in FAQ

- CHANGELOG.md
Fix missing changelog entry in #428
> docs(changelog): add missing changelog entry

- rumqttc/src/client.rs
- rumqttc/src/lib.rs
- rumqttd/src/link/console.rs
- rumqttd/src/router/scheduler.rs
> Reexport RecvError, TryRecvError and RecvTimeoutError

- CHANGELOG.md
- rumqttd/src/link/console.rs
- rumqttd/src/protocol/mod.rs
- rumqttd/src/protocol/v4/disconnect.rs
- rumqttd/src/protocol/v4/mod.rs
- rumqttd/src/protocol/v5/disconnect.rs
- rumqttd/src/protocol/v5/mod.rs
- rumqttd/src/router/routing.rs
- rumqttd/src/server/broker.rs
And add optional properties to `unsubscribe`, `unsuback` and `connack` packet, so its consistent with other packets.
> fix(protocol): Extract out Disconnect packet logic similar to other packets

- rumqttd/src/router/logs.rs
- rumqttd/src/router/routing.rs
- rumqttd/src/router/scheduler.rs
This refactor includes:
- Pre-allocate memory to `HashSet`
- Remove unnecessary checks to see if element is present in our collection
- Efficiently generate vectors using map-collect and `vec![]`
- Use `drain` instead of `mem::replace`!
> refactor(router): remove redundant checks and optimizations 

- rumqttd/src/server/broker.rs
that println! was added in #522 by mistake
> fix(log): use tracing::debug instead of println!

- rumqttc/src/v5/mqttbytes/mod.rs
- rumqttc/src/v5/mqttbytes/v5/subscribe.rs
- rumqttd/src/protocol/v5/subscribe.rs
> fix: add processing of missing Mqtt subscribe options

- rumqttd/README.md
> doc: Instructions for updating log filters via console

- rumqttc/Cargo.toml
- rumqttd/Cargo.toml
ref: https://doc.rust-lang.org/nightly/cargo/reference/features.html#optional-dependencies
> fix(build): remove implicit features

- rumqttd/CHANGELOG.md
- rumqttd/src/main.rs
Print version with `--version`
> fix(cli): add option to show current version

- rumqttd/Cargo.toml
- rumqttd/src/link/remote.rs
- rumqttd/src/router/routing.rs
> add feature flag to allow duplicate clientid

- Cargo.lock
- rumqttd/Cargo.toml
- rumqttd/src/link/console.rs
- rumqttd/src/server/broker.rs
Use `axum` instead of `rouille`
> chore(deps): use axum instead of rouille

- rumqttd/examples/singlenode.rs
- Update `singlenode` example to make a subscription to `#` by default so publish messages are printed.
- Use `tracing-subscriber` instead of `pretty_env_logger` for better log messages
Closes #582
> fix(example): Make a subscription and use tracing

- rumqttc/src/client.rs
- rumqttc/src/eventloop.rs
- Refactor handling of pending requesets in the select loop
- Use .send() instead of pollster in sync client
Miscellaneous (related to maintanance)
- No user facing changes.
> chore: Minor cleanup

- README.md
- rumqttd/CHANGELOG.md
- rumqttd/src/link/remote.rs
- rumqttd/src/router/routing.rs
- (Breaking) Remove retained messages and lastwill: Current implementation does not work correctly. It needs to be re-worked. Till then removing these features.
> Ignore retain and lastwill

- Cargo.lock
Updated `Cargo.lock` file to fix dependabot warnings
- Miscellaneous (related to maintanance)
-  updating `Cargo.lock` file shouldn't affect library users.
> fix: dependabot warnings

- rumqttd/src/segments/mod.rs
> fix: panic when only 1 segment is allowed

- rumqttc/examples/async_manual_acks_v5.rs
- rumqttc/examples/asyncpubsub_v5.rs
- rumqttc/examples/syncpubsub_v5.rs
- rumqttc/examples/syncrecv_v5.rs
- rumqttc/examples/topic_alias.rs
- rumqttc/src/v5/client.rs
- Minor changes to unreleased code.
> fix: Remove redundant use of Option in client API

- rumqttc/CHANGELOG.md
- rumqttc/src/eventloop.rs
- rumqttc/src/v5/eventloop.rs
Use `IntoClientRequest` to create ws & wss upgrade requests with required headers.
> rumqttc: fix: Switch to using IntoClientRequest

- config/rumqttd.conf
Miscellaneous (related to maintanance)
> chore: remove outdated config directory

- Dockerfile
- README.md
- rumqttd/README.md
- Miscellaneous (related to maintanance)
> fix(build/doc): update dockerfile and readme

- rumqttd/CHANGELOG.md
- rumqttd/src/router/routing.rs
> Include reason code in UnsubAck for v5

- rumqttc/README.md
Fix #618 
I don't know if there are additional docs/code to update. Please let me know! 🤗
> docs: remove invalid docs disclaimer

- .github/stale.yml
Related to PR #671 
What has been changed:
- Removed Stale
> chore(github): removed stale

- README.md
I created a package for Archlinux in AUR https://aur.archlinux.org/packages/rumqttd-bin.
Maybe the systemd service is not perfect but works https://git.sr.ht/~mekyt/rumqttd-bin/tree/master/item/rumqtt.service.
> docs: add AUR package in README.md

- .github/PULL_REQUEST_TEMPLATE.md
Miscellaneous (related to maintanance) <- this PR fixes the typo right here!
> fix: typos and grammar

- Cargo.lock
- rumqttc/Cargo.toml
- rumqttd/Cargo.toml
Miscellaneous (related to maintenance)
> build(deps): update dependencies

- Cargo.toml
- rumqttd/src/main.rs
- rumqttd/src/router/logs.rs
- rumqttd/src/router/routing.rs
Miscellaneous (related to maintenance)
> fix(clippy): workspace resolver and unnecessary hashes around raw string literal

- .github/workflows/release.yml
> feat: install cross from git and cleanup

- rumqttc/src/websockets.rs
Improves readability and adherence to the protocol
> revert #726: only expect "mqtt" in response header

- Cargo.lock
- benchmarks/Cargo.toml
- rumqttc/Cargo.toml
- rumqttd/CHANGELOG.md
- rumqttd/Cargo.toml
> update tungstenite and other dependencies

- rumqttc/CHANGELOG.md
- rumqttc/src/v5/mqttbytes/v5/mod.rs
> Make RetainForwardRule public

- rumqttd/CHANGELOG.md
- rumqttd/src/lib.rs
ref: https://github.com/bytebeamio/rumqtt/issues/697#issuecomment-1869055926
-
> pub re-export of Strategy for shared subscriptions

- Cargo.lock
- rumqttc/Cargo.toml
- rumqttc/examples/async_manual_acks.rs
- rumqttc/examples/async_manual_acks_v5.rs
- rumqttc/examples/asyncpubsub.rs
- rumqttc/examples/asyncpubsub_v5.rs
- rumqttc/examples/serde.rs
- rumqttc/examples/subscription_ids.rs
- rumqttc/examples/syncpubsub.rs
- rumqttc/examples/syncrecv.rs
- rumqttc/examples/tls.rs
- rumqttc/examples/tls2.rs
- rumqttc/examples/topic_alias.rs
- rumqttc/examples/websocket.rs
- rumqttc/examples/websocket_proxy.rs
- rumqttc/src/lib.rs
> refactor: clean-up examples

- Cargo.lock
- rumqttd/CHANGELOG.md
- rumqttd/Cargo.toml
- rumqttd/src/link/bridge.rs
- rumqttd/src/server/tls.rs
> chore(rumqttd): Update rustls and friends.

- Cargo.lock
- rumqttc/Cargo.toml
- rumqttd/Cargo.toml
- rumqttd/src/link/console.rs
- rumqttd/src/server/broker.rs
> chore: update dependencies

- rumqttd/CHANGELOG.md
- rumqttd/examples/external_auth.rs
- rumqttd/src/lib.rs
- rumqttd/src/link/remote.rs
> feat(rumqttd): async auth function

- rumqttd/src/link/bridge.rs
ref: https://github.com/bytebeamio/rumqtt/pull/795#discussion_r1484375735
> feat(rumqttd): add Sec1Key and ignore non key items

- .github/workflows/ci.yml
CI update that should save 2GB of space and prevent rustc from stopping tests.
> ci(actions): disable incremental compilation to save space

- .github/workflows/ci.yml
- Cargo.toml
> ci(actions): prevent "out of space" error on github actions ubuntu image

- benchmarks/parsers/v4.rs
- rumqttc/src/framed.rs
- rumqttc/src/mqttbytes/v4/mod.rs
- rumqttc/src/state.rs
- rumqttc/tests/broker.rs
> refactor: `read` and `write` methods on `v4::Packet`

- rumqttc/src/eventloop.rs
- rumqttc/src/framed.rs
- rumqttc/src/proxy.rs
- rumqttc/src/tls.rs
- rumqttc/src/v5/eventloop.rs
> refactor: describe `AsyncReadWrite`

- rumqttc/src/framed.rs
> fix: `readb` should block for 1 packet

- rumqttc/CHANGELOG.md
- rumqttc/src/client.rs
- rumqttc/src/mqttbytes/v4/mod.rs
- rumqttc/src/proxy.rs
- rumqttc/src/v5/client.rs
Fixes #787
use `valid_filter()` to check if filter is valid or not while creating subscribe request.
> fix(rumqttc): validate filters for subscribe.

- rumqttd/CHANGELOG.md
- rumqttd/src/lib.rs
Miscellaneous (related to maintenance): Allow creation of `ConnectionSettings`
> Make external_auth pub available again. 

- rumqttd/CHANGELOG.md
- rumqttd/src/lib.rs
> feat: export `Forward`

- rumqttd/CHANGELOG.md
- rumqttd/src/link/local.rs
> feat: `LinkTx::unsubscribe`

- rumqttc/src/lib.rs
> fixed doc of TlsConfiguration::Simple

- rumqttc/examples/ack_promise_sync.rs
- rumqttc/src/client.rs
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
- rumqttc/src/state.rs
- rumqttc/src/tokens.rs
- rumqttc/src/v5/client.rs
- rumqttc/src/v5/eventloop.rs
- rumqttc/src/v5/mod.rs
- rumqttc/src/v5/state.rs
Implement `Token`s that resolve on completing the handling of a request within the `EventLoop`
> feat: tokens for all requests

- benchmarks/simplerouter/src/protocol/mod.rs
- benchmarks/simplerouter/src/protocol/v4.rs
- benchmarks/simplerouter/src/protocol/v5.rs
- rumqttc/src/mqttbytes/v4/connect.rs
- rumqttc/src/mqttbytes/v4/publish.rs
- rumqttc/src/v5/mqttbytes/v5/connect.rs
- rumqttc/src/v5/mqttbytes/v5/publish.rs
- rumqttc/src/v5/mqttbytes/v5/subscribe.rs
- rumqttc/src/v5/state.rs
- rumqttd/src/protocol/mod.rs
- rumqttd/src/protocol/v4/connect.rs
- rumqttd/src/protocol/v4/publish.rs
- rumqttd/src/protocol/v5/connect.rs
- rumqttd/src/protocol/v5/publish.rs
- rumqttd/src/protocol/v5/subscribe.rs
- rumqttd/src/router/iobufs.rs
> chore: fix clippy warnings
