bytebeamio/rumqtt

- rumq-client/examples/reconnection.rs
- rumq-client/src/eventloop.rs
- rumq-client/src/lib.rs
* Fixes reconnection issue during idle state after a reconnection due to halfopen connection
* Notify network closes and done request streams
* Expose parts of `MqttEventLoop` to control the state before next reconnection
> Reconnection fix

- rumq-cli/Cargo.toml
- rumq-client/Cargo.toml
This reduces the number of indirect dependencies by quite a bit
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
> Bump env-logger dependencies

- rumq-client/examples/gcloud.rs
- rumq-client/examples/pubsub.rs
- rumq-client/examples/reconnection.rs
- rumq-client/examples/smoke.rs
- rumq-client/examples/tls.rs
- rumq-client/src/eventloop.rs
- rumq-client/src/lib.rs
- rumq-core/src/mqtt4/packets.rs
In short: 
- Added so that last_will works
- Removed a lot of trailing spaces / tabs
- Added `new()` methods to Publish and Subscribe
- Added a more descriptive `create_eventloop` that is just using `eventloop()` internally
- Added deprecated flag to eventloop so that it can be renamed in the future without much hassle
> Last will + some changes to names

- rumq-broker/Cargo.toml
- rumq-broker/src/connection.rs
- rumq-broker/src/lib.rs
- rumq-broker/src/router.rs
- rumq-broker/src/state.rs
- rumq-client/Cargo.toml
- rumq-client/src/eventloop.rs
- rumq-client/src/network.rs
- rumq-client/src/state.rs
- rumq-core/Cargo.toml
- rumq-core/src/lib.rs
- rumq-core/src/mqtt4/packets.rs
- Adds dependency on `thiserror`, but also removes `derive-more`
- Adds Error implementation on all enums found with `enum.*Error`
- This also required implementations for Display, which were added in a
best-effort fashion.
Fixes #61
> Impl std::error::Error for a bunch of error enums

- rumq-client/src/eventloop.rs
Not sure how much of `.await` and `?` should be included.
The phrasing "poll it with tokio" sounds very beginnerish, so that might be relevant to include in the same vein.
That has indeed been a change, where it used to neither return a Future not a Result, all errors going inside the Stream.
> Update doc comment

- rumqttc/src/state.rs
This PR fixes a compilation error in the the `rumqttc` crate on the `master` branch:
```
error[E0599]: no associated item named `MAX` found for type `u16` in the current scope
--> /home/dwagner/.cargo/git/checkouts/rumqtt-5c5ad7136a67b3df/b57ffbf/rumqttc/src/state.rs:78:43
|
78 |             incoming_pub: vec![None; u16::MAX as usize + 1],
|                                           ^^^ associated item not found in `u16`
|
help: you are looking for the module in `std`, not the primitive type
|
78 |             incoming_pub: vec![None; std::u16::MAX as usize + 1],
```
I used the following compiler
```
$ rustc --version
rustc 1.41.0
```
> Fix compilation error in state.rs

- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
- rumqttc/src/tls.rs
This allows the caller to easily integrate with rustls-native-certs or webpki-roots to use standard root CA certs, or change other configuration beyond the options currently supported by MqttOptions.
> Allow rustls::ClientConfig to be injected via MqttOptions.

- benchmarks/rumqttasync.rs
- benchmarks/rumqttasyncqos0.rs
- benchmarks/rumqttsync.rs
- rumqttc/examples/asyncpubsub.rs
- rumqttc/src/client.rs
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
Hi!
First of all, thank you all for working on this very nice mqtt library. Looking through the code I was a little bit surprised by the choice that the rumqttc eventloop yielded
```rust
Result<(Option<Incoming>, Option<Outgoing>), ConnectionError>.
```
which made it non-obvious if it could be the case that both an incoming and an outgoing event would be available at the same time and/or if it might be possible that there might be no event at all. This pull request changes the return type to
```rust
Result<Event, ConnectionError>
```
where the event is just
```rust
pub enum Event {
Incoming(Incoming),
Outgoing(Outgoing),
}
```
However, since I'm not familiar with this code, there might be a good reason for the previous design choice, so please don't feel pressured to accept this pull …
> Change return type of rumqttc event loop

- benchmarks/rumqttasync.rs
- benchmarks/rumqttasyncqos0.rs
- rumqttc/examples/asyncpubsub.rs
- rumqttc/src/client.rs
Deriving `Debug` is useful as it may be included in other structs which want to derive `Debug`. The various methods don't need a mutable reference to self as the `async_channel::Sender` is threadsafe.
> Clean up AsyncClient a bit

- rumqttc/Cargo.toml
- rumqttd/Cargo.toml
- rumqttlog/Cargo.toml
Otherwise other people who update their dependency on e.g. rumqttc but
have a Cargo.lock with an old version of mqtt4bytes already will get
build failures.
> Specify correct version of crates within this repository.

- rumqttc/src/framed.rs
- rumqttc/src/lib.rs
PubRel was missing in possible outgoing packets and would panic the program
when publishing with QoS2
> Handle PubRel in outgoing packets

- rumqttc/src/client.rs
This is useful for creating a fake `AsyncClient` for tests, and potentially also for applications which need to mix use of `AsyncClient` with the raw `Sender`s.
> Expose constructor to create AsyncClient from senders.

- rumqttc/src/lib.rs
`PartialEq` is useful for `assert_eq!(...)` in tests.
> Derive more traits for public types.

- rumqttc/src/lib.rs
The code contains an enum `SecurityOptions` which seems to be a leftover of the old rumqtt library and which is not being used anywhere. This PR removes the enum.
> Remove unused enum SecurityOptions

- rumqttd/src/consolelink.rs
- rumqttd/src/lib.rs
If no `[console]` section is provided in the config then the console server will not be started. This allows a more minimal configuration when the console is not needed.
> Make console optional.

- rumqttc/Cargo.toml
- rumqttc/examples/tls.rs
This example loads the system root certiifcates with rustls-native-certs.
Fixes #214.
> Add example of how to use rumttc wih TLS.

- rumqttc/README.md
- rumqttc/src/lib.rs
I can't see any reason why this example has a sleep in the polling loop, it will just slow everything down.
> There shouldn't be any need to sleep between polling the EventLoop.

- rumqttd/Cargo.toml
I missed this in the Tokio 1.0 update (#219). It didn't cause any problems in the tests or anything I tried, but it might be an issue somewhere.
> Update tokio-compat-02 too.

- rumqttc/Cargo.toml
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
I haven't added the new `websocket` feature to the default features, if you want I can update the PR to do that.
Resolves #226.
> client: Move websocket support behind a Cargo feature

- rumqttd/Cargo.toml
- rumqttd/src/bin.rs
**Woop-woop!** That's the sound of da *Windows* police!
The [`pprof` crate](https://lib.rs/crates/pprof) is unfortunately [not compatible with Windows](https://github.com/tikv/pprof-rs/issues/9) as of now, and thus its inclusion prevents the library from being built even if the relevant code is never accessed. It is only "used" in [`rumqttd/src/bin.rs`](https://github.com/bytebeamio/rumqtt/blob/master/rumqttd/src/bin.rs), and even then it really isn't, so it is not what you would necessarily call [essential](https://i.imgur.com/0WXFHtw.png).
This change simply gets rid of the offending piece of code and its dependency. Rejoice, for this lets the library be built on Windows once more!
> Fix compilation on Windows once more

- rumqttc/src/tls.rs
- rumqttd/src/lib.rs
The cause can be something as simple as not having RSA in -----BEGIN RSA PRIVATE KEY-----. It applies both to the client
and server side. Mentioned this in #236
> Handling error cases if the key is parsed but is not valid.

- rumqttd/config/rumqttd.conf
- rumqttd/config/rumqttd0.conf
- rumqttd/config/rumqttd1.conf
- rumqttd/config/rumqttd2.conf
- rumqttd/src/consolelink.rs
- rumqttd/src/lib.rs
The address that the broker and console binds is hardcoded to the v4 any address 0.0.0.0. In order to operate the broker on
a dedicated address or a v6 ip this needs to be added to the configuration. Replace the lonely `port` setting in the configuration with a `std::net::SocketAddr`.
There are host and port configs in `rumqttlog/timestmp.toml` and `rumqttlog/mesh.toml` which I couldn't identify. Looks like outdated stuff.
> Replace hard coded 0.0.0.0 bind of broker and console with configuration option `listen`

- mqttbytes/src/v5/connack.rs
- mqttbytes/src/v5/disconnect.rs
- mqttbytes/src/v5/mod.rs
I added to `mqttbytes` V5 protocol Disconnect Reason Codes and Disconnect Properties as described in [documentation](https://docs.oasis-open.org/mqtt/mqtt/v5.0/csprd01/mqtt-v5.0-csprd01.html#_Toc489530226)
> V5 disconnect packet reason code and properties

- .github/workflows/features.yml
- rumqttd/Cargo.toml
- rumqttd/README.md
- rumqttd/config/rumqttd.conf
- rumqttd/config/rumqttd0.conf
- rumqttd/config/rumqttd1.conf
- rumqttd/config/rumqttd2.conf
- rumqttd/src/lib.rs
By using the `use-native-tls` feature, this crate can now use tokio-native-tls vs tokio-rustls. Discussed this in #257. Turns out it was trivial to add since `tokio` uses the same API for both packages. The only thing that seems like a bummer right now is that it requires use of a `pkcs12` cert rather than 3 separate ones.
> rumqttd: adding optional native-tls support.

- mqttbytes/src/v4/connect.rs
- rumqttd/src/lib.rs
- rumqttd/src/remotelink.rs
Changed:
* Created InvalidServerPass error for pkcs12 password check failure.
* Checking credentials on connection if needed.
* Changed login in ConnectionSettings to be a list rather than a single set of username/password
Added:
* Additional error condition if no valid user/password was found
* Added validate function for Login credentials in codec.
* Checking authentication failure list on initial connection to boot it if it's too soon.
* Propagates device address and AuthenticationAttempts list to Connector & RemoteLink
* Adding or clearing connection from AuthenticationAttempts list depending on password check success
* Setting max lockout duration to 24h (prevent overflow)
> Adding server side password check.

- mqttbytes/src/v4/connect.rs
- mqttbytes/src/v5/connect.rs
I'm trying to use mqttbytes as a library in my C project though Rust FFI, but username and password in Connect::Login as private fields prevent they be visited through FFI. 
Set the username and password fields as pub is straight forward and we have all other packet struct fields as pub too.
> let username and password fields in connect message in public

- rumqttc/src/client.rs
Thank you for welcoming my small contributions in the project.
I love the `mqttc::AsyncClient` implementation as it allows to have access to a single instance from multiple threads if shared as `Arc<AsyncClient>` between them. 
The small change I made removes the requirement to have a Mutex to access the AsyncClient from other threads in case you need to use the `subscribe_many` methods, thus making AsyncClient trully asynchronous. 
The `&mut self` in the `subcribe_many` method signatures was "breaking" the true asynchronous implementation as it was causing it to fail the `Deref` trait on my `Arc<AsyncClient>` when I wanted to use the `subscribe_many()` method. I believe the mutability requirement does not offer any apparent benefits and does not break anything if removed.
So, I just …
> Make mqttc::AsyncClient fully asynchronous

- rumqttc/Cargo.toml
This is required by any crate that depends on `rumqttc` but not `tokio`.
See #294.
> Add missing tokio features: rt, macros, io-util

- benchmarks/clients/rumqttasync.rs
- benchmarks/clients/rumqttasyncqos0.rs
- benchmarks/clients/rumqttsync.rs
- rumqttc/examples/asyncpubsub.rs
- rumqttc/examples/syncpubsub.rs
- rumqttc/examples/tls.rs
- rumqttc/examples/tls2.rs
- rumqttc/src/lib.rs
- rumqttc/src/state.rs
- rumqttc/tests/reliability.rs
Since most libraries use `Duration` to express timeouts, I propose to change the `set_keep_alive` function to consume `Duration`
> Change set_keep_alive to use Duration instead of u16

- rumqttc/src/lib.rs
As the code changes.
The `keep_alive_secs`  URL query parameter should be removed (taken) from the `queries` HashMap when trying to convert to `MqttOptions`.
> Fix keep_alive_secs parameter when converting from URL in MqttOptions

- rumqttc/src/lib.rs
Right now it's impossible to use / match against `rumqttc::tls::Error`, therefore I propose this change
Realted to #323
> Make tls::Error public in rumqttc

- rumqttc/src/eventloop.rs
Currently the `must_use` attribute is being applied to the `Future` instead of `Eventloop::poll()` itself.
> Remove `must_use` attribute over `poll()`

- rumqttc/Cargo.toml
- rumqttc/examples/tls.rs
- rumqttc/src/lib.rs
- rumqttc/src/tls.rs
Update rumqttc to use version 0.20 of rustls and update all dependent crates.
> rumqttc: update rustls to 0.20

- .github/stale.yml
Marks as stale if issues are not active for over 20 days
uses [probot/stale](https://github.com/probot/stale)
> Add stale-issue management bot configuration

- Cargo.lock
- rumqttc/Cargo.toml
- rumqttc/examples/tls.rs
- rumqttc/examples/tls2.rs
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
Closes #305
Enables the compilation of `rumqttc` without rustls/TLS support by using `--no-default-features` flag during compilation. `rustls` support is enabled by default, otherwise can be enabled with `use_rustls` feature flag.
> Make rustls optional

- benchmarks/simplerouter/src/protocol/mod.rs
- rumqttc/src/client.rs
- rumqttc/src/mqttbytes/mod.rs
- rumqttc/src/state.rs
- rumqttc/src/tls.rs
- rumqttd/src/async_locallink.rs
- rumqttd/src/lib.rs
- rumqttd/src/locallink.rs
- rumqttd/src/mqttbytes/mod.rs
- rumqttd/src/network.rs
- rumqttd/src/remotelink.rs
- rumqttd/src/state.rs
Initially I wanted to just add details for the `mqttbytes::Error` in the `StateError`. I continued with other `thiserror::Error` implementations to improve error details.
Something that is not the same everywhere is the formatting style: `text: {0}`, `text {0}` or `text = {0}` are used currently. I could also improve that with this PR but I am not sure with format is preferred. Maybe `text: {0}`?
> Improve Error texts

- rumqttc/src/eventloop.rs
- rumqttc/src/v5/eventloop.rs
Solves #406 
Moving all use of `connection_timeout` up to call for `connect()` to ensure the timeout is applied to the entire connect procedure and not merely to a specific async closure.
> Move timeout to `connect()` call

- CHANGELOG.md
- rumqttc/src/client.rs
- rumqttc/src/mqttbytes/v4/subscribe.rs
> feat: remove code exposing flume errors in `ClientError`

- rumqttc/src/lib.rs
- rumqttc/src/v5/mod.rs
Closes: #426 
This exports are causing `ClientConfig` to be shown as a type coming from `rumqttc` in [docs.rs](https://docs.rs/rumqttc/latest/rumqttc/struct.ClientConfig.html). Uses of this [type](https://docs.rs/rumqttc/latest/src/rumqttc/lib.rs.html#299-304) still expect the correct `tokio_rustls::rustls::ClientConfig` type.
So this could just be a bug in generating docs still not sure if this is the right way to do it, suggestions welcome. 
re: https://github.com/thin-edge/thin-edge.io/pull/1291
> fix(exports): remove leaky `pub use`

- CHANGELOG.md
- rumqttc/src/v5/notifier.rs
Add `try_recv()` which resolves to `Ok` only if it is able to immediately receive an incoming packet.
Else errors out with a special error type `TryRecvError` which has variants to signify if connection is active or dead.
Closes: #430
> feat: Create non-blocking interface for `Notifier`

- rumqttc/Cargo.toml
- rumqttc/src/client.rs
- rumqttc/src/lib.rs
fixes #435 
- `MqttOptions::parse_url` when passed the url for an encrypted protocol, e.g. `mqtts://`, `ssl://` or `wss://` will from now on use `rustls-native-certs::load_native_certs()` to load the certificates from the native cert store.
- Updated documentation
> feat: `MqttOptions::parse_url` uses `rustls-native-certs::load_native_certs()` for encrypted connections

- rumqttc/src/lib.rs
- rumqttc/src/v5/eventloop.rs
Compiling the crate failed when default features were disabled and `url` feature was enabled. That happened due to missing conditinal compilation attributes in URL parsing. This was tested by building `rumqttc` with the following commands:
```sh
cargo build --no-default-features --features=url
cargo build --no-default-features --features=url --features=websocket
```
> fix: allow use of `url` feature without `use-rustls`

- rumqttd/Cargo.toml
`rustls-pemfile` is needed only when `use-rustls` feature is enabled.
> fix: set `rustls-pemfile` dependency as optional

- rumqttc/Cargo.toml
`rustls-native-certs` dependency is needed only when `use-rustls` feature is enabled.
> fix: set `rustls-native-certs` dependency as optional

- rumqttc/src/client.rs
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
- rumqttc/tests/reliability.rs
redo #437 
BREAKING CHANGE: don't expose flume types and handles to send `EventLoop` requests
**Why**: `EventLoop::handle` is determined to be best unexposed as a public interface along with other flume types
Rewrite tests with `AsyncClient`
attributes: @henil
> refactor!: unexpose eventloop handle, unexport flume

- .github/workflows/build.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
Started with testing the available features on their own. Might find mistakes with wrong `#[cfg(feature = …)]` thingies like #440.
Then I noticed they still run on the old `master` branch name which is now `main`. Also fetch dependencies in its own step to have less mixed up output per step.
Also ensure docs are working. It does not seem to work on windows so I disabled it there.
Additionally I switched from the ubuntu-18.04 image to the latest image as 18.04 is deprecated.
> GitHub Action improvements

- rumqttc/src/lib.rs
ignore documentation tests that relies on `use-rustls` dependencies
> fix: ignore doc-test for ci sanity

- rumqttc/src/mqttbytes/topic.rs
Improves validation of filters by checking rule in 4.7.1.3 ('+' must occupy an entire level of the filter).
~~Improves usability by adding a `get_wildcards(topic, filter) -> Option(Vec<&str>)` function that returns `None` if the topic doesn't match the filter, and otherwise returns `Some(v)` where v contains the fragments of the topic corresponding to filter wildcards.~~ removed as requested.
> fix(mqttbytes): when present wildcard must occupy entire topic level

- rumqttc/src/v5/mod.rs
- rumqttc/src/v5/notifier.rs
Fixes #456
Enable use of `TryRecvError` variants
> fix: export enum `TryRecvError`

- CHANGELOG.md
- Cargo.lock
- rumqttc/Cargo.toml
- rumqttc/src/client.rs
Continued from discussion on #430
Implement `recv` `try_recv` `recv_timeout` for `Connection` similar to `v5::Notifier::try_recv`
CC @sirver
> feat: Implement `recv` `try_recv` `recv_timeout` for `Connection`

- rumqttc/src/v5/eventloop.rs
- rumqttc/src/v5/state.rs
Solves #459
Currently incoming `ConnAck` packets(first received) are being unconditionally dropped and connected applications have no means of receiving the information that might be contained in them.
> fix: Route `Incoming::ConnAck` onto `Notifier`

- CHANGELOG.md
- Cargo.lock
- benchmarks/Cargo.toml
- rumqttc/Cargo.toml
- rumqttd-old/Cargo.toml
- rumqttd/Cargo.toml
- update to newer version was needed because older version of this crates depended on vulnerable version of other crates
- found unused dependencies found using https://crates.io/crates/cargo-udeps
> fix(dependencies): Update libraries to newer version and remove unused dependencies

- Cargo.lock
- rumqttd/Cargo.toml
The TLS implementation is selected by either feature `use-rustls` or `use-native-tls`. The selection of the TLS implementation is forwarded to the `request` dependency which otherwise defaults to `native-tls`.
> Forward TLS implementation selection to reqwest

- Cargo.lock
- rumqttd/Cargo.toml
- rumqttd/src/link/shadow.rs
Continues #488 
rumqttd doesn't depend on `reqwest`/`ws_stream_tungstenite` anymore.
Feature gate dependency on `tokio-util` and `futures-util` to `websockets` builds only
> fix: remove unused and feature gate websocket dependencies

- rumqttd/src/router/scheduler.rs
Initially, we were finding out indexes of elements which we want to remove, and then we will remove it by 
```rust
// ....
for idx in idxs {
self.data_requests.remove(idx);
}
```
The problem with this approach is, when we call `remove(idx)`, it shifts other elements too. Thus indexes of other elements which we want to remove get changed. And due to this, we end up filtering wrong elemets.
To fix this, we can use [retain](https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.retain) method to retain only those elements which does not match our filter, which is what we intend to do.
```rust
self.data_requests.retain(|data_req| data_req.filter != filter);
```
> fix Tracker: fix unregister_data_requests in Tracker to properly filter

- CHANGELOG.md
- rumqttc/src/client.rs
- rumqttc/src/v5/client.rs
`timeout` function uses `Sleep` internally, but as we are outside of Tokio runtime context, it will fail to spawn it and thus will panic! [reference](https://docs.rs/tokio/latest/tokio/time/fn.timeout.html#panics).
To fix it, we can explicitly enter the runtime by using [enter](https://docs.rs/tokio/latest/tokio/runtime/struct.Runtime.html#method.enter) method.
Fixes Issue: #467
> fix(client): enter tokio runtime context before calling timeout in recv_timeout

- .github/workflows/build.yml
- rumqttd/src/server/tls.rs
Modify/remove code that was causing clippy to trip CI workflow
- Fix clippy warnings within rumqttd
- Turn off clippy run against benchmarks
> fix: clippy warnings

- CHANGELOG.md
- rumqttc/examples/syncrecv.rs
- rumqttc/examples/syncrecv_v5.rs
- rumqttc/src/client.rs
- rumqttc/src/v5/client.rs
Closes #496 
Enter the runtime context within `Connection::try_recv()` in order to allow the creation and passing of a noop waker for the instantaneous polling of associated future.
> fix: enter runtime context for `now_or_never()` within `try_recv`

- CHANGELOG.md
- rumqttd/src/link/console.rs
- rumqttd/src/link/local.rs
- rumqttd/src/link/remote.rs
- rumqttd/src/router/iobufs.rs
- rumqttd/src/router/logs.rs
- rumqttd/src/router/routing.rs
- rumqttd/src/server/broker.rs
Enhance tracing in rumqttd
- Re-organize spans basis of importance of context information they carry. The span tree has three levels. Level 0 has coarse, high-level information. Level 2 has fine, low-level information. The tree looks like:  
```
|- incoming (level 0)
|    |- incoming_connect (level 1)
|    |- incoming_payload
|    |    |- publish (level 2)
|    |    |- subscribe
|    |    |- ...
|    |- incoming_disconnect
|- outgoing (level 0)
|    |- outgoing_ack (level 1)
|    |- outgoing_publish
```
- ~Refactor `routing::forward_device_data()`~ (Added #507 for this)
- Make tracing events more human-readable
- Remove fields from tracing events that are present in enclosing tracing spans
> chore(rumqttd): Make tracing events human-readable

- CHANGELOG.md
- rumqttd/src/lib.rs
required so consumer of meter requests can match over the type of `Meter` that was received back
> refactor: make router::Meter public

- rumqttd/src/router/logs.rs
- rumqttd/src/router/routing.rs
we where already not allowing subscriptions with QoS::Exactlyonce https://github.com/bytebeamio/rumqtt/blob/fad4882356230365d707d9093a7a26cd66cb7e89/rumqttd/src/router/routing.rs#L1192-L1194
disallow QoS::EactlyOnce publishes as well for now.
> Disconnect clients that send QoS2 publishes

- rumqttd/src/main.rs
- also add a subcommand to generate a config file on demand. 
for example
```
rumqttd generate-config > rumqttd.toml
```
> feat(cli): Make configuration file optional

- .github/workflows/build.yml
- .github/workflows/main.yml
Instead of running a different job for each combination of os and feature flag (i.e. 24 jobs in total). It is changed so it run all the feature flag tests in the same job using [cargo-hack](https://github.com/taiki-e/cargo-hack) (i.e. 3 jobs in total). Also use [rust-cache](https://github.com/Swatinem/rust-cache) to cache builds of dependencies.
Current runtime of CI could take anywhere from 45-60 mins. Optimized flow take around 25-30 min depending on if things are cached or not. This can be optimized further by removing things like doc tests and moving those to workflow of main branch because currently there are not alot of changes in doc tests and its something that can be fixed easily after PR is merged. But will do a separate PR for that.
Note: This workflow tests for more feature …
> fix(CI): Optimize Github CI workflows

- benchmarks/clients/common.rs
This was remove in #530 by mistake because it had dependency on `ruqmttd-old`, and pull request's CI only runs `cargo check` on `rumqttd` and `rumqttc` so it was not caught there.
So add back the parts that are used by other tests.
> fix(ci): only remove parts which had dependency on rumqttd-old

- CHANGELOG.md
- rumqttc/src/eventloop.rs
- rumqttc/src/state.rs
- rumqttc/src/v5/eventloop.rs
- rumqttc/src/v5/state.rs
- rumqttd/src/router/iobufs.rs
- rumqttd/src/segments/mod.rs
`ConnectionError` has a variant named `ConnectionRefused` which should be used instead.
> refactor!: Remove `Connect` from `ConnectionError::StateError`

- rumqttc/examples/async_manual_acks.rs
- rumqttc/examples/async_manual_acks_v5.rs
- rumqttc/examples/asyncpubsub.rs
- rumqttc/examples/asyncpubsub_v5.rs
- rumqttc/examples/syncpubsub.rs
- rumqttc/examples/syncpubsub_v5.rs
- rumqttc/examples/syncrecv_v5.rs
- rumqttc/examples/tls.rs
- rumqttc/examples/websocket.rs
`.poll()` method on rumqttc clients tries to reconnect to the server incase of any error. and we where printing events in a loop, which was causing client to print error in an infinite loop on terminal if broker was not running. 
it is now changed to stop the program and print it in the case client gets an error.
Also change port to `1884` for MQTTv5 examples.
> fix(example): Stop printing error in loop

- rumqttc/src/v5/eventloop.rs
- rumqttc/src/v5/framed.rs
> fix(v5): send last_will and login info with connect

- Cargo.lock
- rumqttc/Cargo.toml
- rumqttd/Cargo.toml
The [release history](https://github.com/rustls/pemfile#release-history) states no API changes. Using the current stable release means getting all the bugfixes.
As currently both `0.3` and `1` are used both dependencies are built when using rumqttc. Without `0.3` only `1` will be built, removing `0.3` from the lock file.
Other dependencies are also not the latest version but I havnt looked into them.
> build: use stable release of rustls-pemfile

- Cargo.lock
- rumqttc/src/client.rs
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
- rumqttc/src/state.rs
- rumqttc/src/tls.rs
- rumqttc/src/v5/eventloop.rs
- rumqttc/src/v5/mod.rs
- rumqttc/tests/broker.rs
- rumqttc/tests/reliability.rs
changes made:
- connection_timeout is moved to `NetworkOptions`
- connection_timeout is removed from `Url` feature.
- `ConnectionError` now has specific variant for type of Timeout, `FlushTimeout` and `NetworkTimeout` instead of generic `Timeout` for both.
> fix(rumqttc): Add timeouts to network flushes and clean state properly on network failures

- rumqttd/src/link/local.rs
When multi-tenancy is enabled, client id is prefixed with tenant name in `Connection` object. It is not prefixed in `Outgoing` and `Incoming` objects. Because of inconsistency, there is bug where we disconnect connections with same client id but different tenants. This PR fixes that.
> fix: client id with tenant prefix should be set globally

- docs/CoC.md
Fixed Typo in docs/CoC.md file
> docs: correct spelling of conduct

- .github/workflows/release.yml
Update Github CI so it generates and publishes release binaries. Currently CI expected tag starting with `R`. But we changed our release process to create a release with tag `rumqttd x.x.x` so it stopped working.
Also update actions used.
Test run: https://github.com/henil/rumqtt-dev/actions
Result: https://github.com/henil/rumqtt-dev/releases/tag/rumqttd-0.12.13
> fix(ci): build release binaries when tag with particular format is pushed

- rumqttc/CHANGELOG.md
- rumqttc/examples/async_manual_acks_v5.rs
- rumqttc/src/v5/eventloop.rs
- rumqttc/src/v5/state.rs
- rumqttd/src/lib.rs
Please read `CONTRIBUTING.md` if you are contributing for the first time.
Remove use of box for enclosing `Incoming` in `mod v5`
Fixes #581 
Please delete options that are not relevant.
> fix: remove unnecessary box

- Cargo.lock
- benchmarks/Cargo.toml
Fix for https://github.com/advisories/GHSA-mc8h-8q98-g5hr
> fix: dependabot warning by upgrading version of pprof used

- rumqttd/CHANGELOG.md
- rumqttd/rumqttd.toml
- rumqttd/src/lib.rs
- rumqttd/src/link/mod.rs
- rumqttd/src/server/broker.rs
- When `port` is specified `listen` is ignored.
- When both are not specific default socket address used is `127.0.0.1:9042`
- `port` is deprecated and will be removed in future breaking release.
> feat(prometheus): add a field in config file to specify listen socket address

- .gitignore
- Cargo.lock
- rumqttc/CHANGELOG.md
- rumqttc/Cargo.toml
- rumqttc/examples/tls.rs
- rumqttc/src/tls.rs
- rumqttd/Cargo.toml
- rumqttd/src/link/bridge.rs
- rumqttd/src/server/tls.rs
With rustls 0.21.0 release see: <https://www.memorysafety.org/blog/rustls-new-features/>, two new features cames along:
> The first big feature is support for TLS certificates containing IP addresses. Rustls can now be used to set up TLS connections addressed by IP rather than a domain name. This is useful for things like Kubernetes pods, which often use IP addresses instead of domain names, and for DNS over HTTPS/TLS which need an IP address for the server to avoid circular dependency on name resolution. TLS certificates for IP addresses have been the most heavily requested feature for quite a while now and it's great to have it completed.
> The second big feature is support for [RFC8446 C.4 client tracking prevention](https://www.rfc-editor.org/rfc/rfc8446#appendix-C.4). This means that …
> feat: update rustls to `0.21.0` and tokio-rustls to `0.24`

- rumqttd/CHANGELOG.md
- rumqttd/src/link/bridge.rs
- rumqttd/src/link/console.rs
- rumqttd/src/link/local.rs
- rumqttd/src/link/remote.rs
- rumqttd/src/link/shadow.rs
- rumqttd/src/protocol/mod.rs
- rumqttd/src/protocol/v4/mod.rs
- rumqttd/src/router/connection.rs
- rumqttd/src/router/logs.rs
- rumqttd/src/router/mod.rs
- rumqttd/src/router/routing.rs
- rumqttd/src/server/broker.rs
This PR adds support for MQTTv5 related features, topic alias and message expiry.
- Allow clients to set and use topic alias
- Broker can also set topic alias ( if supported by client ). If client specifies maximum topic alias to use, broker will use topic aliases for that client.
- Discard expired messages ( expired messaged mean time spent waiting >= message expiry interval )
- before forwarding publish packets, update message expiry interval to original value - time spent 
> Topic alias and message expiry support in broker

- CHANGELOG.md
- rumqttd/CHANGELOG.md
- rumqttd/src/protocol/v5/mod.rs
fix (v5):  **Include unsubscribe package**
- Unsubscribe packet included in match arms
- Such packets will not proceeds to `unreachable!()`
> feat: read unsubscribe packet in v5

- rumqttc/CHANGELOG.md
- rumqttc/src/client.rs
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
- rumqttc/src/mqttbytes/v4/disconnect.rs
- rumqttc/src/mqttbytes/v4/mod.rs
- rumqttc/src/mqttbytes/v4/ping.rs
- rumqttc/src/mqttbytes/v4/puback.rs
- rumqttc/src/mqttbytes/v4/pubcomp.rs
- rumqttc/src/mqttbytes/v4/publish.rs
- rumqttc/src/mqttbytes/v4/pubrec.rs
- rumqttc/src/mqttbytes/v4/pubrel.rs
- rumqttc/src/mqttbytes/v4/suback.rs
- rumqttc/src/mqttbytes/v4/subscribe.rs
- rumqttc/src/mqttbytes/v4/unsuback.rs
- rumqttc/src/mqttbytes/v4/unsubscribe.rs
- rumqttc/src/state.rs
- ~~Stop `.poll()` from reconnecting after an `disconnect()` call~~
- Enforce `max_outgoing_packet_size` on v3 client
> rumqttc: Enforce max packet size

- rumqttc/src/mqttbytes/v4/unsubscribe.rs
- rumqttc/src/state.rs
- Fixed len() on v4 Unsubscribe packet
- `cargo fmt` on `outgoing_max_packet_size_check` test
- Not relevant. Fixing an unreleased bug.
> rumqttc: Fixed len() on v4 Unsubscribe packet

- rumqttd/src/segments/mod.rs
- rumqttd/src/segments/segment.rs
- rumqttd/src/server/broker.rs
Fix some typos in docstrings and comments in rumqttd in the modules `segements` and `server`.
- Miscellaneous (related to maintanance)
> docs(rumqttd): Fix typos in segments and server

- rumqttd/architecture.md
Enhanced the description of the current architecture of `rumqttd`
Miscellaneous (related to maintanance)
This isn't relevant as it's a documentation change.
> docs(rumqttd/architecture): added ontology description and feature description

- rumqttc/CHANGELOG.md
- rumqttc/src/v5/eventloop.rs
- rumqttc/src/v5/mod.rs
I am trying to connect to an AWS IoT Shadow via MQTT and SigV4 but couldn't find any way to add additional headers to the request. This adds a way to modify the request before connecting.
Example usage:
```rust
mqtt_options.set_request_modifier(move |request| {
let credential_provider = credential_provider.clone();
let region = region.clone();
async move {
let request_config = RequestConfig {
request_ts: SystemTime::now(),
region: &SigningRegion::from(region.clone()),
service: &SigningService::from_static("iotdata"),
payload_override: None,
};
let (parts, body) = request.into_parts();
let mut request: http::Request<SdkBody> = http::Request::from_parts(parts, SdkBody::empty());
let signer = SigV4Signer::new();
signer.sign(
&OperationSigningConfig::default_config(),
&request_config, …
```
> Allow modifying websocket requests.

- Cargo.lock
- rumqttc/Cargo.toml
- rumqttd/Cargo.toml
This PR modifies the dependency on `flume` to only enable its `async` feature instead of all features that are enabled by default. The motivation for this change is that neither `rumqttc` nor `rumqttd` need to select between (i.e., wait for any one of multiple) messages from multiple channels. However, the `select` feature of `flume` is enabled by default, together with its `eventual-fairness` feature that ensures that channels in a selector cannot make other ones starve. To do so, a source of randomness is required which is obtained through additional dependencies that this PR aims to avoid for both users and developers of `rumqtt`.
Miscellaneous (related to maintanance)
> Disable unsused features from `flume` dependency

- rumqttd/CHANGELOG.md
- rumqttd/src/link/bridge.rs
- rumqttd/src/link/console.rs
- rumqttd/src/link/local.rs
- rumqttd/src/link/remote.rs
- rumqttd/src/server/broker.rs
Support for constructing `LinkRx`/`LinkTx` using `LinkBuidler`.
```rust
let (link_tx, link_rx, notification) = LinkBuilder::new(&client_id, router_tx)
.tenant_id(tenant_id) // None by default
.clean_session(clean_session) // true by default
.last_will(lastwill) // None by default
.dynamic_filters(dynamic_filters) // false by default
.topic_alias_max(topic_alias_max) // 0 by default
.build()?;
```
Breaking change (fix or feature that would cause existing functionality to not work as expected)
> Builder pattern for constructing Link

- Cargo.lock
- benchmarks/Cargo.toml
- benchmarks/simplerouter/Cargo.toml
- rumqttc/Cargo.toml
- rumqttd/Cargo.toml
Bump itoa from 0.4 to 1.0
Bump pprof from 0.11 to 0.12
Bump pretty_env_logger from 0.4 to 0.5
Bump rustls-webpki from 0.100.1 to 0.101.1
Bump color-backtrace from 0.4 to 0.5
Bump x509-parser from 0.9.2 to 0.15
Bump parking_lot from 0.11.2 to 0.12.1
Bump metrics from 0.20.1 to 0.21.1
Bump metrics-exporter-prometheus from 0.11.0 to 0.12.1
> build(deps): Bump dependencies to latest

- utils/mqttverifier/README.md
- utils/mqttverifier/package-lock.json
- utils/mqttverifier/package.json
- utils/mqttverifier/printer.js
- utils/mqttverifier/suback/s0.js
- utils/mqttverifier/subscribe/s0.js
- utils/mqttverifier/subscribe/s1.js
- utils/mqttverifier/unsuback/s0.js
- utils/mqttverifier/unsubscribe/s0.js
- utils/mqttverifier/unsubscribe/s1.js
Related to PR #671 and PR #677
What has been changed:
- `rumqttverifier`
Better structure (and README) with type info/suggestions via JSDoc
Note that in `unsuback/s0.js` I've fixed an invalid property for that type of message.
> chore(mqttverifier): fix typo and better structure with jsdoc type

- Cargo.lock
- rumqttd/CHANGELOG.md
- rumqttd/Cargo.toml
- rumqttd/rumqttd.toml
- rumqttd/src/lib.rs
- rumqttd/src/router/logs.rs
- rumqttd/src/router/mod.rs
- rumqttd/src/router/routing.rs
- rumqttd/src/router/shared_subs.rs
This PR adds support for shared subscriptions. This PR adds support for shared subscriptions in broker with the ability to use multiple strategies for it. The available strategies are as follows:
- round_robin (Default): 	In order of subscription, moving from first to last to first etc.
- random: 	Random selection among all subscribers, using `rand` crate to select a random client.
- sticky: 	Always send to the last selected subscriber, only moving when a client is no longer available.
Strategies are specified in the router config and by default commented but easily changeable.
This PR supersedes #628 and was made by me and @swanandx. 👍🏼 
> Shared subscriptions with configurable strategy

- Cargo.toml
- benchmarks/Cargo.toml
- benchmarks/simplerouter/Cargo.toml
- rumqttc/Cargo.toml
- rumqttc/src/lib.rs
- rumqttc/src/v5/mod.rs
- rumqttd/Cargo.toml
Related to PR #671
What has been changed:
- Enhance `cargo workspace` utilization while avoiding repetitions
- Updated release profile
```toml
[profile.release]
codegen-units = 1 # Better optimization
lto = true # Link time optimization
strip = true # Stripping
```
> chore: enhance cargo workspace and release build

- rumqttc/CHANGELOG.md
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
- rumqttc/src/v5/mod.rs
Allows the network connection to be optionally bound to a specific interface.
See also: https://docs.rs/tokio/latest/tokio/net/struct.TcpSocket.html#method.bind_device
> rumqttc: Add bind_device to NetworkOptions to enable TCPSocket.bind_device()

- CHANGELOG.md
- rumqttc/CHANGELOG.md
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
- rumqttc/tests/reliability.rs
This PR removes the requirement that the keep alive timeout be at
least 5 seconds. This is in keeping with the MQTT spec, which
states that the keep alive value should be between 0 and 65535.
A value of 0 indicates that no keep-alive pings are sent to the
broker.
Issue: #643 - Keep Alive has an arbitrary limit
- [ X ] Formatted with `cargo fmt`
- [ X ] Make an entry to `CHANGELOG.md` if its relevant of user of the library. If its not relevant mention why.
> fix(Event Loop): Allow keep-alives <= 5 secs

- Cross.toml
Related to PR #671 and PR #673
What has been changed:
- Configure `cross` for enhanced cross compilation supporting `x86_64-unknown-linux-musl` and `aarch64-unknown-linux-musl` and more...
> feat: configure cross to support x86_64 and aarch64 for linux/musl

- rumqttc/src/v5/state.rs
Miscellaneous (related to maintenance)
Change the ping timing debug log from a multi line string to a single line with the use of the `Debug` impl of `Duration`. Multi line logs screw a log stream in regards of readability. This PR doesn't contain any API change and just affect debug logs - no need to add a noisy changelog entry.
> feat(rumqttc): Replace multi line debug log with single line

- rumqttd/CHANGELOG.md
- rumqttd/src/router/logs.rs
- rumqttd/src/router/routing.rs
Publish properties were not being recorded for qos2. This PR aims to fix that behaviour.
> Publish properties in qos2 publishes

- README.md
- rumqttd/CHANGELOG.md
- rumqttd/src/link/local.rs
- rumqttd/src/link/remote.rs
- rumqttd/src/router/connection.rs
- rumqttd/src/router/mod.rs
- rumqttd/src/router/routing.rs
- rumqttd/src/server/broker.rs
Bring back support for will messages and also support will delays.
We separate disconnection and publishing will messages. Will messages are published _after_ disconnection ( and cleanup ). 
NOTE: This can be considered breaking as signature of some fns in rumqttd are changed. In reality, this shouldn't affect any of the user, but still.
> Will messages and will delay interval

- Cargo.lock
- rumqttc/Cargo.toml
- rumqttc/src/tls.rs
- rumqttd/Cargo.toml
- rumqttd/src/link/bridge.rs
This PR does:
- `cargo update` to remove webpki ( _rustls-webpki_  ) / other sec vulns
- use released version of `ws_stream_tungstenite` as patched version might have some edge cases which aren't tested
-  replace deprecated functions
> chore: cargo update and replace deprecated functions

- rumqttd/CHANGELOG.md
- rumqttd/src/link/local.rs
- rumqttd/src/router/connection.rs
- rumqttd/src/router/routing.rs
Construct Connection using builder pattern to avoid passing too many arguments to `Connection::new`
> feat: non-consuming builder for Connection

- rumqttc/CHANGELOG.md
- rumqttc/src/websockets.rs
This PR adds up on #724 and fixes behavior incase the header contains multiple subprotocols listed in a comma-delimited format.
> Validate "mqtt" exists in comma delimited subprotocol header 

- rumqttd/CHANGELOG.md
- rumqttd/src/link/console.rs
This PR changes functionality of console's /config. previously it was returning console settings, now it prints router config!
> console endpoint /config prints router config

- rumqttc/CHANGELOG.md
- rumqttc/Cargo.toml
As described in [rustsec](https://rustsec.org/advisories/RUSTSEC-2023-0065), there is a vulnerability in older versions of tungstenite. This library is used in the chain of dependencies of rumqtt. This change up-steps those dependencies.
> update tungstenite dependencies for security purpose

- rumqttd/CHANGELOG.md
- rumqttd/src/lib.rs
- rumqttd/src/main.rs
- rumqttd/src/server/broker.rs
This PR makes v4 config optional so that users can specify v4 and/or v5 config ( or ws ) as per their use case.
This will allow user to use only v5 if they wish.
> Make v4 config optional

- .github/workflows/release.yml
- rumqttd/CHANGELOG.md
- rumqttd/Cargo.toml
- rumqttd/src/server/broker.rs
This PR does following:
- enable websocket feature by default
- remove old "websockets" feature
- log warning if ws config is getting ignored
> Enable websocket feature by default

- rumqttd/CHANGELOG.md
- rumqttd/src/lib.rs
- rumqttd/src/main.rs
- rumqttd/src/server/broker.rs
Fixes #672 . 
Changes:
- make console settings optional
- instead of blocking on console in `start()`, we block on joining thread handle of spawned servers.
- New feature (non-breaking change which adds functionality)
> console configuration should be optional

- rumqttc/examples/async_manual_acks.rs
- Allow code to continue after first loop finishes
> fix(rumqttc/examples): Fix rumqttc async_manual_acks.rs

- rumqttc/CHANGELOG.md
- rumqttc/src/eventloop.rs
- rumqttc/src/v5/eventloop.rs
Make public the `EventLoop::clean` method to allow for storage of pending requests onto disk in bytebeamio/uplink
> feat: expose `EventLoop::clean`

- benchmarks/clients/rumqttsync.rs
- rumqttc/CHANGELOG.md
- rumqttc/examples/serde.rs
- rumqttc/examples/syncpubsub.rs
- rumqttc/examples/syncrecv.rs
- rumqttc/src/client.rs
I realized that the synchronous client might not actually need to take `&mut` self instead of `&self` here. I think reducing the requirements on this would make it more ergonomic. 
Also with respect to a breaking change, I'm not actually sure that this is one. I don't think it is, but am not really sure how to tell.
Breaking change (fix or feature that would cause existing functionality to not work as expected)
> feat: Synchronous Client: Remove mut from methods

- rumqttd/CHANGELOG.md
- rumqttd/src/lib.rs
- rumqttd/src/main.rs
- rumqttd/src/server/tls.rs
-   `rsa_` prefix allows current certs (such as the ones generated by provision, which I think are PKCS#1), i.e `BEGIN RSA PRIVATE KEY`
-  `ec_` or `ecc_` prefix with the `BEGIN EC PRIVATE KEY`
- no prefix for universal private key files, of the form `BEGIN PRIVATE KEY`
Anyway, someone more senior in this project can help make those decisions. I don't fully understand if there was a reason for hardcoding RSA in the code, but my use case requires ECC (embedded environments)
> Allow ECC Key Configuration with rustls

- rumqttc/CHANGELOG.md
- rumqttc/examples/tls2.rs
- rumqttc/src/lib.rs
- rumqttc/src/tls.rs
Breaking Change
This PR lets users of rumqttc use any of the Rustls supported key encodings [RSA (PKCS#1), PKCS#8, SEC1].  
This issue addresses #751 
I left the `Key` enum as is to prevent a breaking change, however it does no longer matter if the user choses `RSA` or `ECC`. For a cleaner API I think the `Key` enum could be removed.
> rumqttc: TLS Key encoding fix

- rumqttc/CHANGELOG.md
- rumqttc/src/lib.rs
- rumqttc/src/tls.rs
client certificate is optional while using rumqttc with rustls. But with native-tls, it is required to specify certificates! 
Client authentication certificates should be optional for native-tls as well, this PR makes the required changes for it :rocket: 
> optional client certificates while using native-tls

- rumqttc/CHANGELOG.md
- rumqttc/src/eventloop.rs
- rumqttc/src/v5/eventloop.rs
calling drain on receiver while doing cleanup would help us in preventing data loss to some extend!
- New feature (non-breaking change which adds functionality)
> drain pending Request from channel while cleanup

- rumqttd/CHANGELOG.md
- rumqttd/rumqttd.toml
- rumqttd/src/lib.rs
- rumqttd/src/link/remote.rs
* Breaks config API by renaming `auth` to `static_auth`.
This solves two problems we currently have with rumqttd:
* The ability to get client id on new connections, when a new connection happens.
* Allow hooks into our external auth service.
> Adds external auth capabilities.

- .github/workflows/build.yml
- rumqttd/src/remove_me.rs
CI isn't caching properly. let's say a PR is opened, job runs and saves cache with key "-c4efedb3", now if I push a commit ( editing changelog ), it has restore key of "-fda4c98d.." so it never finds the cache which it should have!
Basically, we are never seeing an cache hit.
This solves two things:
- use keys with `runner.os` ( for cache hits )
- set `RUSTFLAG: -D warnings" globally instead of just clippy ( otherwise the cache is invalidated and project is rebuilt every time! )
> fix rust-cache with proper key and global RUSTFLAG

- rumqttd/examples/external_auth.rs
adds example setup for external auth in rumqttd
> Example for external authentication setup

- rumqttc/CHANGELOG.md
- rumqttc/src/v5/mod.rs
> update request modifier fn type to impl send and sync

- rumqttc/CHANGELOG.md
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
- rumqttc/src/v5/mqttbytes/v5/mod.rs
currently websocket request modifier is only present in v5 client, this PR aims to bring it to v4 client as well.
- New feature (non-breaking change which adds functionality)
> Add websocket request modifier for v4 client

- rumqttc/CHANGELOG.md
- rumqttc/src/eventloop.rs
- rumqttc/src/v5/eventloop.rs
Situation earlier:
1. `EventLoop` has pending packets yet to be processed.
2. `EventLoop::clean` is called.
3. `EventLoop::poll` has lost some packets which were earlier pending.
This can be solved with a queue in place of the pending iter.
> fix: ensure pending packets are not lost on `EventLoop::clean`

- rumqttd/CHANGELOG.md
- rumqttd/src/server/broker.rs
* Disconnect by peer shouldn't be an error. Peer initiated disconnects should be logged as good faith operations.
Miscellaneous (related to maintenance)
> rumqttd: Changes peer initiated disconnect logs to info.

- rumqttc/CHANGELOG.md
- rumqttc/src/client.rs
- rumqttc/src/v5/client.rs
A lot of my team's code uses the synchronous client. I'd like to be able to easily write tests using a Fake Mqtt client. One easy way to do this for unit tests is by using something like the `from_senders` method that's available on the `AsyncClient`. This PR adds a `from_sender` method for the sync client which can be used to write tests like the one I wrote in this PR. 
It also updates a stale comment on the async client.
> Add `from_senders` for the Sync Client

- rumqttd/CHANGELOG.md
- rumqttd/src/link/network.rs
MQTT keepalive duration set by the client wasn't being used. This PR aims to fix this issue :)
> fix(rumqttd): use keepalive duration when reading from network

- rumqttc/CHANGELOG.md
- rumqttc/src/state.rs
- rumqttc/src/v5/framed.rs
- rumqttc/src/v5/state.rs
fix typos in error messages and rename Incomming to Incoming
> fix(rumqttc): Fix typos in StateError

- rumqttc/src/mqttbytes/topic.rs
- rumqttc/src/v5/mqttbytes/mod.rs
This PR aims to:
- optimize the filter validation by avoiding allocation during validation
- optimize the topic validation by using binary operators instead of multiple conditional statements
This is just optimization and doesn't affect user API, so CHANGELOG entry isn't required.
> feat(rumqttc): optimize topic and filter validation

- rumqttd/CHANGELOG.md
- rumqttd/src/router/graveyard.rs
- rumqttd/src/router/routing.rs
we were setting `session_present` flag as `true` even when there was no previous session stored ( due to rumqttd storing matrices ). 
This PR aims to fix it by making session state as Option, so we can distinguish between just storing matrices and storing the session state. 
> fix(rumqttd): fix session present flag in connack

- rumqttc/CHANGELOG.md
- rumqttc/src/lib.rs
- rumqttc/src/v5/mod.rs
> feat(rumqttc): allow empty client id

- Cargo.lock
- rumqttc/CHANGELOG.md
- rumqttc/Cargo.toml
- rumqttc/examples/tls.rs
- rumqttc/src/lib.rs
- rumqttc/src/tls.rs
- rumqttc/src/v5/mod.rs
> chore(rumqttc): update to latest versions of rustls and friends

- benchmarks/simplerouter/src/protocol/v4.rs
- benchmarks/simplerouter/src/protocol/v5.rs
- rumqttc/CHANGELOG.md
- rumqttc/src/mqttbytes/v4/connect.rs
- rumqttc/src/mqttbytes/v4/publish.rs
- rumqttd/src/protocol/v4/publish.rs
Solves #816 
`Connect::write` was returning wrong value in couple places.
> Make sure `write` returns the number of bytes it writes everywhere

- rumqttd/CHANGELOG.md
- rumqttd/src/protocol/v4/connect.rs
- rumqttd/src/protocol/v4/publish.rs
- rumqttd/src/protocol/v5/connect.rs
write method wasn't returning the number of bytes read correctly for some types in rumqttd.
> Make Type::write return correct value for rumqttd

- rumqttc/src/mqttbytes/v4/connack.rs
- rumqttc/src/mqttbytes/v4/connect.rs
- rumqttc/src/mqttbytes/v4/mod.rs
- rumqttc/src/v5/mqttbytes/v5/connect.rs
- rumqttc/src/v5/mqttbytes/v5/mod.rs
- rumqttc/src/v5/mqttbytes/v5/ping.rs
> feat: implement `Packet::size` for v4/v5

- Cargo.lock
- rumqttc/CHANGELOG.md
- rumqttc/Cargo.toml
- rumqttc/src/eventloop.rs
- rumqttc/src/framed.rs
- rumqttc/src/lib.rs
- rumqttc/src/mqttbytes/mod.rs
- rumqttc/src/mqttbytes/v4/codec.rs
- rumqttc/src/mqttbytes/v4/mod.rs
- rumqttc/src/state.rs
- rumqttc/src/v5/eventloop.rs
- rumqttc/src/v5/framed.rs
- rumqttc/src/v5/mod.rs
- rumqttc/src/v5/mqttbytes/mod.rs
- rumqttc/src/v5/mqttbytes/v5/codec.rs
- rumqttc/src/v5/mqttbytes/v5/mod.rs
- rumqttc/src/v5/state.rs
- rumqttc/tests/reliability.rs
As discussed in #814 this simplifies `Network` using `Framed` and `Codec`
* `mqttbytes::Error` is no longer `Clone, Copy, PartialEq, Eq` and 2 new variants, for io and packet size limit
* Refactors different parts of the codebase to regularize and simplify.
* Deprecates bulk read and moves write buffer into `Network`, which might lead to issues with packets in the buffer being dropped when an error is faced. But this seems like premature-optimization to be frank
> refactor: simplify `Network`with `Framed<.., Codec>`

- Cargo.lock
- rumqttd/CHANGELOG.md
- rumqttd/Cargo.toml
- rumqttd/src/link/remote.rs
Fixes https://github.com/bytebeamio/rumqtt/issues/796
Password Authentication in constant time using subtle::ConstantTimeEq
> fix(rumqttd): Implement constant-time password comparison

- rumqttc/CHANGELOG.md
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
- rumqttc/src/v5/framed.rs
- rumqttc/src/v5/mod.rs
> refactor: use `Login` to store credentials in MqttOptions

- rumqttc/src/state.rs
- rumqttc/src/v5/state.rs
> refactor: break out if publish is unsolicited

- rumqttc/CHANGELOG.md
- rumqttc/src/framed.rs
- rumqttc/src/state.rs
- rumqttc/src/v5/framed.rs
- rumqttc/src/v5/state.rs
> fix: don't panic on connection closure

- rumqttc/src/v5/eventloop.rs
fixes: https://github.com/bytebeamio/rumqtt/pull/825#issuecomment-2041392647
Bug fix
> fix: v5 doesn't write outgoing packets onto network

- rumqttc/CHANGELOG.md
- rumqttc/Cargo.toml
- rumqttc/src/state.rs
- rumqttc/src/v5/state.rs
- rumqttd/src/router/alertlog.rs
- rumqttd/src/router/mod.rs
- rumqttd/src/router/routing.rs
- rumqttd/src/segments/mod.rs
- rumqttd/src/server/mod.rs
> fix: ordering of events returned on `poll()`

- rumqttc/CHANGELOG.md
- rumqttc/examples/async_manual_acks_v5.rs
- rumqttc/src/v5/eventloop.rs
- rumqttc/src/v5/mod.rs
Fixing issue https://github.com/bytebeamio/rumqtt/issues/853
* Added `session_expiry_interval` support for MQTT V5 connection,
> feat: add MQTT v5 connection `session_expiry_interval` support

- rumqttc/CHANGELOG.md
- rumqttc/src/eventloop.rs
- rumqttc/src/v5/eventloop.rs
bug fix: #849
An isolated PUBACK packet is being sent to the broker after the client reconnects.
> fix: filter unexpected PubAck in event loop pending queue.

- Cargo.lock
- rumqttd/Cargo.toml
Disable default feature for `metrics-exporter-prometheus`, because we do not use the feature `push-gateway`, which introduce `native-tls` to the lib.
> Disable default feature for `metrics-exporter-prometheus`

- rumqttc/src/client.rs
- rumqttc/src/v5/client.rs
- rumqttc/src/v5/mod.rs
- Not making an entry in the changelog because this is a regression that was introduced on `main` and hasn't found it's way into a release yet.
This fixes the issue with `subscribe_many` as detailed in #837.
I know that that PR was closed in favor of #813 but that apparently didn't go anywhere for months so I suggest to merge a smaller scoped fix in the meantime. This might also prevent others like me from having to search for this Bug for hours just to find out it was already known and had a fix that just wasn't merged.
To recap: The issue is that `subscribe_many` consumes the iterator over topics in order to validate them, leaving no actual topics left to subscribe to. This then always leads to an `EmptySubscription` error in the …
> rumqttc: Fix: subscribe_many cannot work as implemented, always causing EmptySubscription error.

- rumqttc/CHANGELOG.md
- rumqttc/src/v5/eventloop.rs
- rumqttc/src/v5/state.rs
Bug fix (non-breaking change which fixes an issue): https://github.com/bytebeamio/rumqtt/issues/875
In v5, filtered error cases so ACK fail cases are not disconnecting.
> Remove SubAck/UnsubAck/PubAck/PubRec/PubRel/PubComp reason code errors from critical state error

- Cargo.lock
- rumqttd/CHANGELOG.md
Get's rid of the following error:
```
Checking time v0.3.34
error[E0282]: type annotations needed for `Box<_>`
--> /home/devdutt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
|
83 |     let items = format_items
|         ^^^^^
...
86 |     Ok(items.into())
|              ---- type must be known at this point
|
help: consider giving `items` an explicit type, where the placeholders `_` are specified
|
83 |     let items: Box<_> = format_items
|              ++++++++
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
```
> ci: update for clippy box error

- Cargo.lock
- rumqttc/CHANGELOG.md
- rumqttc/Cargo.toml
> Update dependencies for rumqttc.

- rumqttc/CHANGELOG.md
- rumqttc/src/client.rs
- rumqttc/src/v5/client.rs
- Miscellaneous (related to maintenance): docs spelling fix
In [this](https://docs.rs/rumqttc/0.24.0/rumqttc/struct.Connection.html) example, `EventLoop` is spelled wrongly as `EvenLoop`.
Note: I have not ran this, as doing so would also change other lines which I have not altered, should I do so?
Note: Have done so, but not sure if it is appropiate.
> docs: fix spelling for EventLoop

- rumqttc/examples/ack_promise.rs
- rumqttc/examples/ack_promise_sync.rs
- rumqttc/examples/ack_promise_v5.rs
- rumqttc/src/client.rs
- rumqttc/src/lib.rs
- rumqttc/src/state.rs
- rumqttc/src/tokens.rs
- rumqttc/src/v5/client.rs
- rumqttc/src/v5/mod.rs
- rumqttc/src/v5/state.rs
- rumqttc/tests/reliability.rs
1. Tokens should resolve with acknowledgement packets, in an expected manner.
2. Manual acknowledgement request tokens should resolve on associated completion states
3. enums `AckOfPub` and `AckOfAck`
Based on suggestions from @cratertinney https://github.com/bytebeamio/rumqtt/pull/916#issuecomment-2672703936
> fix: token interfaces

- rumqttd/CHANGELOG.md
- rumqttd/src/link/network.rs
Bug fix (non-breaking change which fixes an issue) 
Closes https://github.com/bytebeamio/rumqtt/issues/945.
Closes https://github.com/bytebeamio/rumqtt/issues/948.
> fix: set default network timeout as `Duration::MAX` instead of zero.

- rumqttc/CHANGELOG.md
- rumqttc/src/lib.rs
- rumqttc/src/v5/mod.rs
Other fields have respective setters, client_id has not, and I find it useful.
It's just a field setter function....
> feat(rumqttc): add MqttOptions::set_client_id method

- rumqttd/CHANGELOG.md
- rumqttd/src/lib.rs
- rumqttd/src/server/broker.rs
- rumqttd/src/server/mod.rs
Publicly export `Server`, `Router` and `LinkType`.
I don't really see a problem with making these types `pub`, the constructor for `Server` is pub already but not accessible from outside the crate afaik.
As-is, calling `Broker::start` and thus spawning a new runtime for each config panics inside already async contexts. With this PR new Servers can just be spawned with `tokio::spawn` or `my_runtime::spawn` instead.
New feature
> feat(rumqttd): Make Server public

- rumqttc/CHANGELOG.md
- rumqttc/src/v5/mod.rs
- Bug fix (non-breaking change which fixes an issue), fixes #985
> fix(rumqttc): Make v5::Connection return types public

- rumqttc/CHANGELOG.md
- rumqttc/Cargo.toml
- rumqttc/src/eventloop.rs
- rumqttc/src/lib.rs
- rumqttc/src/proxy.rs
- rumqttc/src/tls.rs
- rumqttc/src/v5/eventloop.rs
- rumqttc/src/v5/mod.rs
Add new feature 'use-rustls-no-provider' which uses rustls but does not enable the default features so that the consumer can choose which crypto backend to use (ring, or rustls-openssl, etc) without being
forced to compile aws_lc_rs.
Because it is a new feature, this should be backwards compatible. Ideally, this crate should not have used default = true at all but just removing it could break some clients that expect rumqttc to run
without explicitly specifying the dependency. Worse, adding 'default-features = False' would allow the clients to compile but panic during runtime with
Could not automatically determine the process-level CryptoProvider from Rustls crate features.
Call CryptoProvider::install_default() before this point to select a provider manually, or make sure exactly one of …
> feat(rumqttc): add use-rustls-no-provider feature
